### ISSUE TITLE
cant set -Xmx properly

### ISSUE THREAD

**Issue by darmbrust** [torquebox/jruby9-maven-plugins#2]
Trying to set the memory limits via -Xmx4G, and finding that I can't, because it is always putting in its own value (why would this be hardcoded?)

[INFO] Execute:Java13CommandLauncher: Executing '/opt/java/jdk_x64_1.8.0_65/jre/bin/java' with arguments:
'-cp'
''
'-cp'
'/mnt/STORAGE/repository/org/jruby/jruby-complete/9.0.4.0/jruby-complete-9.0.4.0.jar'
'-Xmx384m'
'-Xmx4G'

where did the 384m come from?

The plugin shouldn't specify any max at all by default, just let the JVM select... it will do a much better job than 384m.

**Comment by darmbrust** [comment]
root cause is actually over here:  https://github.com/torquebox/jruby-maven-plugins/issues/83

**Comment by mkristian** [comment]
you are right - I will remove the default -Xmx settings. it should work by setting `-Xmx4096m` :)

ah - you found the AntLAuncher already

**Comment by mkristian** [comment]
fixed via e7c12a3d0e9a738abaf164bfc39eb2c548674fe6

and release version 0.3.1 of those plugins
