### ISSUE TITLE
rspecs not executed under windows

### ISSUE THREAD

**Issue by dav9** [torquebox/jruby9-maven-plugins#3]
When using the jrubyExecExample and commenting out all executions except the rspec one I get: 

[INFO] Finished in 0.006 seconds (files took 0.323 seconds to load)
[INFO] 0 examples, 0 failures

The one_specs.rb is not executed

When running rspec in the example folder:

rspec
.

Finished in 0.001 seconds (files took 0.20602 seconds to load)
1 example, 0 failures

**Comment by dav9** [comment]
Manually triggering the rspec via the rspec and gems in target, produces the same result:

> set GEM_PATH=c:\git\jruby9-maven-plugins\jruby9-exec-maven-plugin\src\it\jrubyExecExample\target\rubygems-jruby9-exec-maven-plugin

C:\git\jruby9-maven-plugins\jruby9-exec-maven-plugin\src\it\jrubyExecExample>java -cp ;C:.m2\repository\org\jruby\jruby-complete\9.0.5.0\jruby-complete-9.0.5.0.jar org.jruby.Main target\rubygems\bin\rspec
No examples found.

Finished in 0.008 seconds (files took 0.449 seconds to load)
0 examples, 0 failures

After some digging, in the sources of ExecMojo, I've added <args>spec</args> to the rspec execution configuration and now I get: 

[INFO] Finished in 0.016 seconds (files took 0.903 seconds to load)
[INFO] 1 example, 0 failures

**Comment by mkristian** [comment]
@dav9 could tell me what exactly did you change to get it working ?
